### ISSUE TITLE
CapFacility.R hard coded working directory

### ISSUE THREAD

**Issue by evelynmitchell** [jmsallan/linearprogramming#1]
It mentions 
  setwd("~/Dropbox/VOS/01-Sources/LP/JMSL")
Which is unlikely to work for anyone but jmsallan, because we don't have your dropbox.
In addition, you may not want to put your R environment, from a programming experiment, in the directory of a vendor supplied piece of library code.

**Comment by jmsallan** [comment]
Evelyn,

It is true that you don't have access to my dropbox, but in this case you don't need to acces it to run the code. In fact, the script consists in a function that calls a solver from the Rglpk library. Thanks for making this point, so I will suppress references to setting working directories in the following commit.
